# Generated by Django 4.1.3 on 2022-12-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='atendido',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
