# Generated by Django 4.1.3 on 2022-12-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_reserva_atendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='atendido',
            field=models.DateTimeField(null=True),
        ),
    ]
