# Generated by Django 4.1.3 on 2022-11-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_reserva_hora_servicio_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
