# Generated by Django 4.1.3 on 2022-11-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_reserva_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hora',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='reserva',
            field=models.DateField(),
        ),
    ]
