# Generated by Django 4.1.3 on 2022-11-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_reserva_hora_alter_reserva_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
